### ISSUE TITLE
platform-ui-stable-5.0.x is not suitable for platform-community-5.0.0-RC02

### ISSUE THREAD

**Issue by trendchaser4u** [exoplatform/platform-ui#58]
I tried to build a UI theme with platform-ui-stable-5.0.x branch, i referred official documentation from the exo to build the theme. Since the build and installation succeeded but i cannot able to see the theme name in the list of site configuration.

**Comment by thomasdelhomenie** [comment]
Hello @trendchaser4u 
It is better to use the forum for such questions : https://community.exoplatform.com/portal/intranet/forum
Also please provide startup logs.
Thanks

**Comment by trendchaser4u** [comment]
@thomasdelhomenie  okey :) closing this issue.
